#!/usr/bin/env python3
"""Build and validate the sparse CAS-only addition to the bundled Atari OS."""
from pathlib import Path
import os,re,subprocess,hashlib,json
R=Path(__file__).resolve().parents[1]
G=R/'generated';G.mkdir(exist_ok=True)
ca=os.environ.get('CA65','ca65');ld=os.environ.get('LD65','ld65')
subprocess.run([ca,str(R/'cassette/runtime.s'),'-o',str(G/'cas.o')],check=True)
subprocess.run([ld,'-C',str(R/'cassette/runtime.cfg'),str(G/'cas.o'),'-o',str(G/'cas.bin'),'-Ln',str(G/'cas.lbl')],check=True)
body=(G/'cas.bin').read_bytes();start=0xc6a0
rom=bytes(int(x,16) for x in re.findall(r'0x([\da-fA-F]{2})',(R/'firmware/engine/osrom.h').read_text()))
assert len(rom)==16384 and rom[start-0xc000:start-0xc000+len(body)]==b'\xff'*len(body)
assert rom[0x2459:0x245c]==bytes.fromhex('4c f2 e7')
assert rom[0x247a]==rom[0x247d]==0x4c
boot=bytes([0,1,0,7,9,7,0x4c,start&255,start>>8,0x60])
def array(name,b):return 'static const unsigned char '+name+'[]={\n'+','.join('0x%02x'%v for v in b)+'\n};\n'
(G/'cas_runtime.h').write_text('/* Generated by tools/build_cas_runtime.py */\n#define CAS_RUNTIME_ADDRESS 0xc6a0\n'+array('cas_runtime',body)+array('cas_boot_sector',boot))
(G/'cas-rom.bin').write_bytes(rom[:start-0xc000]+body+rom[start-0xc000+len(body):])
(G/'cas-runtime.json').write_text(json.dumps({'address':hex(start),'length':len(body),'base_os_sha256':hashlib.sha256(rom).hexdigest(),'runtime_sha256':hashlib.sha256(body).hexdigest()},indent=2)+'\n')
print('CAS runtime: %d bytes at $%04X; reserved filler and original vectors verified.'%(len(body),start))
